#!/usr/bin/env php
<?php
define('BASE_PATH', __DIR__);
require_once __DIR__ . '/vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();
require_once __DIR__ . '/app/Cli/Console.php';
exit((new App\Cli\Console())->run($argv));
