# Favilla one-command quickstart (Docker, Windows PowerShell 5.1+).
#
# Generates a .env with fresh random keys on first run (never overwrites an
# existing one), downloads docker-compose.yml if missing (so it also works
# without cloning the repo), then starts the stack.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File quickstart.ps1          # web installer
#   powershell -ExecutionPolicy Bypass -File quickstart.ps1 -Auto   # hands-off boot
#   powershell -ExecutionPolicy Bypass -File quickstart.ps1 -Demo   # -Auto + demo content
#
param([switch]$Auto, [switch]$Demo)
if ($Demo) { $Auto = $true }

$ErrorActionPreference = 'Stop'
$composeUrl = 'https://raw.githubusercontent.com/Myth70/favilla/main/docker-compose.yml'
$appPort = if ($env:APP_PORT) { $env:APP_PORT } else { '8080' }

function Get-RandomHex([int]$Bytes) {
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return -join ($buf | ForEach-Object { $_.ToString('x2') })
}

# -- Prerequisites -------------------------------------------------------------
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host 'Error: docker not found. Install it first: https://docs.docker.com/get-docker/'
    exit 1
}
docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error: the 'docker compose' plugin is missing. See https://docs.docker.com/compose/install/"
    exit 1
}

# -- Compose file (enables the no-clone path) -----------------------------------
if (-not (Test-Path 'docker-compose.yml')) {
    Write-Host 'docker-compose.yml not found here - downloading it from the Favilla repo...'
    Invoke-WebRequest -Uri $composeUrl -OutFile 'docker-compose.yml' -UseBasicParsing
}

# -- .env with random keys (first run only) -------------------------------------
if (Test-Path '.env') {
    Write-Host 'Existing .env found - keeping it as is.'
} else {
    Write-Host 'Generating .env with fresh random keys...'
    $appKey = Get-RandomHex 32
    $backupKey = Get-RandomHex 32
    $dbPass = Get-RandomHex 16
    do { $dbRootPass = Get-RandomHex 16 } while ($dbRootPass -eq $dbPass)  # must differ

    $stamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd')
    $envContent = @"
# Favilla Docker environment - generated by quickstart.ps1 on $stamp
#
# KEEP THIS FILE SAFE. APP_KEY protects encrypted fields and BACKUP_ENCRYPTION_KEY
# protects your backups: losing them means losing access to that data.
# All available settings: see .env.example in the repo.

APP_URL=http://localhost:$appPort
APP_PORT=$appPort

APP_KEY=$appKey
BACKUP_ENCRYPTION_KEY=$backupKey

DB_PASS=$dbPass
DB_ROOT_PASS=$dbRootPass
"@
    # UTF-8 WITHOUT BOM: a BOM would corrupt the first variable name for compose.
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) '.env'), $envContent, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host '  .env written.'
}

# -- Start ----------------------------------------------------------------------
if ($Auto) { $env:AUTO_MIGRATE = 'true' }
if ($Demo) { $env:DEMO_DATA = 'true' }

Write-Host 'Pulling the image and starting containers...'
docker compose up -d
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host ''
Write-Host '----------------------------------------------------------------'
Write-Host "  Favilla is starting:  http://localhost:$appPort"
Write-Host ''
if ($Auto) {
    Write-Host '  Hands-off boot: schema and seed data load on an empty database.'
    Write-Host '  Login: admin / Admin123!  - CHANGE THIS PASSWORD at first login.'
    if ($Demo) { Write-Host '  Demo content loads too (sample projects, documents, chats).' }
} else {
    Write-Host '  Open the URL in your browser to finish setup (web installer).'
}
Write-Host ''
Write-Host '  Logs:     docker compose logs -f app'
Write-Host '  Stop:     docker compose down'
Write-Host '  Upgrade:  docker compose pull; docker compose up -d'
Write-Host '----------------------------------------------------------------'
