#!/usr/bin/env bash
#
# Favilla one-command quickstart (Docker).
#
# Generates a .env with fresh random keys on first run (never overwrites an
# existing one), downloads docker-compose.yml if missing (so it also works
# without cloning the repo), then starts the stack.
#
# Usage:
#   bash quickstart.sh          # start, then finish setup in the web installer
#   bash quickstart.sh --auto   # hands-off boot: schema + seed load on an
#                               # empty DB, login admin / Admin123!
#   bash quickstart.sh --demo   # like --auto, plus demo content (sample
#                               # projects, documents, chats, test users)
#
set -euo pipefail

COMPOSE_URL="https://raw.githubusercontent.com/Myth70/favilla/main/docker-compose.yml"
APP_PORT="${APP_PORT:-8080}"

AUTO=false
DEMO=false
for arg in "$@"; do
    case "$arg" in
        --auto) AUTO=true ;;
        --demo) AUTO=true; DEMO=true ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "Unknown option: $arg (try --help)" >&2
            exit 1
            ;;
    esac
done

# ── Prerequisites ────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
    echo "Error: docker not found. Install it first: https://docs.docker.com/get-docker/" >&2
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    echo "Error: the 'docker compose' plugin is missing. See https://docs.docker.com/compose/install/" >&2
    exit 1
fi

# ── Compose file (enables the no-clone path) ─────────────────────────────────
if [ ! -f docker-compose.yml ]; then
    echo "docker-compose.yml not found here — downloading it from the Favilla repo..."
    curl -fsSLo docker-compose.yml "$COMPOSE_URL"
fi

# ── .env with random keys (first run only) ───────────────────────────────────
rand_hex() { # $1 = bytes
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    else
        od -vN "$1" -An -tx1 /dev/urandom | tr -d ' \n'
    fi
}

if [ -f .env ]; then
    echo "Existing .env found — keeping it as is."
else
    echo "Generating .env with fresh random keys..."
    APP_KEY="$(rand_hex 32)"
    BACKUP_ENCRYPTION_KEY="$(rand_hex 32)"
    DB_PASS="$(rand_hex 16)"
    DB_ROOT_PASS="$(rand_hex 16)"
    while [ "$DB_ROOT_PASS" = "$DB_PASS" ]; do  # must differ (see compose)
        DB_ROOT_PASS="$(rand_hex 16)"
    done

    cat > .env <<EOF
# Favilla Docker environment — generated by quickstart.sh on $(date -u +%Y-%m-%d)
#
# KEEP THIS FILE SAFE. APP_KEY protects encrypted fields and BACKUP_ENCRYPTION_KEY
# protects your backups: losing them means losing access to that data.
# All available settings: see .env.example in the repo.

APP_URL=http://localhost:${APP_PORT}
APP_PORT=${APP_PORT}

APP_KEY=${APP_KEY}
BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}

DB_PASS=${DB_PASS}
DB_ROOT_PASS=${DB_ROOT_PASS}
EOF
    chmod 600 .env 2>/dev/null || true
    echo "  .env written (permissions 600)."
fi

# ── Start ────────────────────────────────────────────────────────────────────
if $AUTO; then
    export AUTO_MIGRATE=true
fi
if $DEMO; then
    export DEMO_DATA=true
fi

echo "Pulling the image and starting containers..."
docker compose up -d

echo
echo "──────────────────────────────────────────────────────────────"
echo "  Favilla is starting:  http://localhost:${APP_PORT}"
if $AUTO; then
    echo
    echo "  Hands-off boot: schema and seed data load on an empty database."
    echo "  Login: admin / Admin123!  — CHANGE THIS PASSWORD at first login."
    if $DEMO; then
        echo "  Demo content loads too (sample projects, documents, chats)."
    fi
else
    echo
    echo "  Open the URL in your browser to finish setup (web installer)."
fi
echo
echo "  Logs:     docker compose logs -f app"
echo "  Stop:     docker compose down"
echo "  Upgrade:  docker compose pull && docker compose up -d"
echo "──────────────────────────────────────────────────────────────"
