-- ============================================================================
-- Favilla v2.0.2 — Schema consolidato definitivo
-- ============================================================================
-- Generato dal DB reale pulito — 2026-04-16
-- Fonte di verità unica per: php database/migrate.php --fresh
-- Totale: 63 tabelle
-- Consolidato aggiornato — 2026-05-01 (integrate migration 025–030 + Contatti + HelpOnline)
-- Consolidato aggiornato — 2026-07-04 (integrate migration Blog, Documenti,
--   Progetti, Teams + allineamento a drift non tracciato: user_weather_preferences)
-- Totale: 100 tabelle
--
-- NOTA: tutte le migration progressive storiche sono state cristallizzate
-- qui. Nuove migration progressive vanno create solo per evoluzioni future.
-- ============================================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS `app_settings` (
  `key` varchar(100) NOT NULL,
  `value` text DEFAULT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'string',
  `group` varchar(50) NOT NULL DEFAULT 'general',
  `label` varchar(200) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`key`),
  KEY `idx_settings_group` (`group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `status` enum('backlog','todo','in_progress','review','done') NOT NULL DEFAULT 'todo',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  `due_date` date DEFAULT NULL,
  `due_time` time DEFAULT NULL,
  `color` varchar(20) DEFAULT NULL,
  `position` int(10) unsigned NOT NULL DEFAULT 0,
  `completed_at` timestamp NULL DEFAULT NULL,
  `calendar_event_id` int(10) unsigned DEFAULT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `last_reminded_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_task_user_status` (`user_id`,`status`),
  KEY `idx_task_user_board` (`user_id`,`deleted_at`,`position`),
  KEY `idx_task_due_date` (`due_date`),
  KEY `idx_task_position` (`position`),
  KEY `idx_task_calendar` (`calendar_event_id`),
  CONSTRAINT `tasks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `task_checklist` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `task_id` int(10) unsigned NOT NULL,
  `text` varchar(500) NOT NULL,
  `is_done` tinyint(1) NOT NULL DEFAULT 0,
  `position` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_task_checklist_task` (`task_id`),
  CONSTRAINT `task_checklist_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `task_tag_map` (
  `task_id` int(10) unsigned NOT NULL,
  `tag_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`task_id`,`tag_id`),
  KEY `tag_id` (`tag_id`),
  CONSTRAINT `task_tag_map_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `task_tag_map_ibfk_2` FOREIGN KEY (`tag_id`) REFERENCES `task_tags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `task_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `color` varchar(20) NOT NULL DEFAULT '#6c757d',
  `user_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_att_tag_unique` (`name`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `task_tags_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `action` varchar(100) NOT NULL,
  `entity` varchar(100) DEFAULT NULL,
  `entity_id` int(10) unsigned DEFAULT NULL,
  `old_value` text DEFAULT NULL,
  `new_value` text DEFAULT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_audit_user` (`user_id`),
  KEY `idx_audit_entity` (`entity`,`entity_id`),
  KEY `idx_audit_created` (`created_at`),
  KEY `idx_audit_action` (`action`),
  CONSTRAINT `audit_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `backup_history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `format` varchar(8) NOT NULL DEFAULT 'sqlgz',
  `size_bytes` int(10) unsigned NOT NULL DEFAULT 0,
  `table_count` int(10) unsigned NOT NULL DEFAULT 0,
  `databases_json` longtext DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `backup_history_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `calendar_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `start_datetime` datetime NOT NULL,
  `end_datetime` datetime DEFAULT NULL,
  `all_day` tinyint(1) NOT NULL DEFAULT 0,
  `color` varchar(20) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `visibility` enum('personal','role','public') NOT NULL DEFAULT 'personal',
  `visible_to_role` int(10) unsigned DEFAULT NULL,
  `reminder_minutes` int(10) unsigned DEFAULT NULL,
  `recurrence_rule` varchar(255) DEFAULT NULL,
  `recurrence_end` datetime DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  `reminder_sent_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cal_dates` (`start_datetime`,`end_datetime`),
  KEY `idx_cal_visibility` (`visibility`,`visible_to_role`),
  KEY `idx_cal_created_by` (`created_by`),
  KEY `visible_to_role` (`visible_to_role`),
  KEY `idx_calendar_events_category` (`category`),
  KEY `idx_cal_reminder` (`reminder_minutes`,`reminder_sent_at`,`start_datetime`),
  KEY `idx_cal_recurrence_end` (`recurrence_end`),
  CONSTRAINT `calendar_events_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `calendar_events_ibfk_2` FOREIGN KEY (`visible_to_role`) REFERENCES `roles` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `changelogs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `version` varchar(20) NOT NULL COMMENT 'Semver es. 1.2.0',
  `title` varchar(255) NOT NULL,
  `notes` text NOT NULL,
  `release_date` date NOT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT 0,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `version` (`version`),
  KEY `fk_changelogs_user` (`created_by`),
  KEY `idx_release_date` (`release_date`),
  KEY `idx_is_published` (`is_published`),
  CONSTRAINT `fk_changelogs_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `changelog_translations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `changelog_id` int(10) unsigned NOT NULL,
  `locale` varchar(10) NOT NULL,
  `title` varchar(255) NOT NULL,
  `notes` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_changelog_translations` (`changelog_id`,`locale`),
  CONSTRAINT `fk_changelog_translations` FOREIGN KEY (`changelog_id`) REFERENCES `changelogs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `contacts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `categoria_id` int(10) unsigned DEFAULT NULL,
  `nome` varchar(255) NOT NULL,
  `cognome` varchar(255) DEFAULT NULL,
  `azienda` varchar(255) DEFAULT NULL,
  `ruolo` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `telefono_alt` varchar(50) DEFAULT NULL,
  `indirizzo` text DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `geocoding_source` enum('manual','osm') DEFAULT NULL,
  `geocoded_at` timestamp NULL DEFAULT NULL,
  `sito_web` varchar(500) DEFAULT NULL,
  `linkedin` varchar(500) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `facebook` varchar(500) DEFAULT NULL,
  `whatsapp` varchar(50) DEFAULT NULL,
  `telegram` varchar(255) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `tags` varchar(500) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `preferito` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_contacts_user` (`user_id`),
  KEY `idx_contacts_cat` (`categoria_id`),
  KEY `idx_contacts_nome` (`nome`),
  KEY `idx_contacts_geo` (`latitude`,`longitude`),
  CONSTRAINT `contacts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `contacts_ibfk_2` FOREIGN KEY (`categoria_id`) REFERENCES `contact_categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `contact_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `nome` varchar(100) NOT NULL,
  `colore` varchar(7) NOT NULL DEFAULT '#6c757d',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_cat_user` (`user_id`),
  CONSTRAINT `contact_categories_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `contact_recurrences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `contatto_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `tipo` enum('compleanno','anniversario','evento') NOT NULL DEFAULT 'evento',
  `titolo` varchar(255) NOT NULL,
  `data_ricorrenza` date NOT NULL,
  `annuale` tinyint(1) NOT NULL DEFAULT 1,
  `anno_riferimento` smallint(5) unsigned DEFAULT NULL,
  `promemoria_giorni_prima` tinyint(3) unsigned NOT NULL DEFAULT 7,
  `notifica_giorno_stesso` tinyint(1) NOT NULL DEFAULT 1,
  `crea_evento_calendario` enum('no','prossimo','annuale') NOT NULL DEFAULT 'no',
  `calendario_event_id` int(10) unsigned DEFAULT NULL,
  `last_notified_year` smallint(5) unsigned DEFAULT NULL,
  `note` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_ric_contatto` (`contatto_id`),
  KEY `idx_ric_user` (`user_id`),
  KEY `idx_ric_data` (`data_ricorrenza`),
  CONSTRAINT `contact_recurrences_ibfk_1` FOREIGN KEY (`contatto_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `contact_recurrences_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `contact_shares` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `contatto_id` int(10) unsigned NOT NULL,
  `role_id` int(10) unsigned NOT NULL,
  `shared_by_user_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contact_shares` (`contatto_id`,`role_id`),
  KEY `idx_contact_shares_role` (`role_id`),
  KEY `fk_contact_shares_user` (`shared_by_user_id`),
  CONSTRAINT `fk_contact_shares_contatto` FOREIGN KEY (`contatto_id`)       REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_contact_shares_role`     FOREIGN KEY (`role_id`)           REFERENCES `roles` (`id`)    ON DELETE CASCADE,
  CONSTRAINT `fk_contact_shares_user`     FOREIGN KEY (`shared_by_user_id`) REFERENCES `users` (`id`)    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `data_retention_policies` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entity` varchar(100) NOT NULL COMMENT 'Human-readable entity name',
  `description` varchar(255) DEFAULT NULL,
  `table_name` varchar(100) NOT NULL COMMENT 'DB table to clean',
  `date_column` varchar(100) NOT NULL DEFAULT 'created_at' COMMENT 'Date column for age check',
  `retention_days` int(10) unsigned NOT NULL DEFAULT 90,
  `action` enum('delete','anonymize') NOT NULL DEFAULT 'delete',
  `anonymize_fields` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Fields to replace with [RIMOSSO] when action=anonymize' CHECK (json_valid(`anonymize_fields`)),
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `last_run_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_retention_entity` (`entity`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `document_bindings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `module` varchar(50) NOT NULL,
  `operation` varchar(50) NOT NULL,
  `label` varchar(200) NOT NULL,
  `template_id` int(10) unsigned NOT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_document_bindings_module_op` (`module`,`operation`),
  KEY `template_id` (`template_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_document_bindings_module` (`module`),
  CONSTRAINT `document_bindings_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `report_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `document_bindings_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `file_shares` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `file_id` int(10) unsigned NOT NULL,
  `target_type` enum('user','role') NOT NULL,
  `target_id` int(10) unsigned NOT NULL,
  `permission` enum('view','edit') NOT NULL DEFAULT 'view',
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_shares_unique` (`file_id`,`target_type`,`target_id`),
  KEY `created_by` (`created_by`),
  KEY `idx_file_shares_file` (`file_id`),
  KEY `idx_file_shares_target` (`target_type`,`target_id`),
  CONSTRAINT `file_shares_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `file_shares_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `file_versions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `file_id` int(10) unsigned NOT NULL,
  `version_no` int(10) unsigned NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `mime_type` varchar(150) NOT NULL,
  `extension` varchar(20) DEFAULT NULL,
  `size_bytes` bigint(20) unsigned NOT NULL,
  `checksum_sha256` varchar(64) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_versions_file_ver` (`file_id`,`version_no`),
  KEY `created_by` (`created_by`),
  KEY `idx_file_versions_file` (`file_id`),
  CONSTRAINT `file_versions_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `file_versions_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `files` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `directory` varchar(100) NOT NULL DEFAULT 'files',
  `mime_type` varchar(100) NOT NULL,
  `extension` varchar(20) NOT NULL,
  `size_bytes` int(10) unsigned NOT NULL,
  `checksum_sha256` varchar(64) DEFAULT NULL,
  `folder` varchar(200) NOT NULL DEFAULT '',
  `description` varchar(500) DEFAULT NULL,
  `tags` varchar(500) DEFAULT NULL,
  `visibility` enum('private','internal') NOT NULL DEFAULT 'private',
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stored_name` (`stored_name`),
  KEY `idx_files_owner` (`created_by`,`deleted_at`),
  KEY `idx_files_vis` (`visibility`,`deleted_at`),
  KEY `idx_files_folder` (`folder`(100),`deleted_at`),
  KEY `idx_files_created` (`created_at`),
  KEY `idx_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_files_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `help_modules` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `module_key` varchar(100) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `label` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `audience_default` varchar(50) NOT NULL DEFAULT 'user',
  `locale_default` varchar(10) NOT NULL DEFAULT 'it',
  `route_name` varchar(150) DEFAULT NULL,
  `permission_slug` varchar(120) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_help_modules_key` (`module_key`),
  KEY `idx_help_modules_name` (`module_name`),
  KEY `idx_help_modules_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `help_entries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `module_id` int(10) unsigned NOT NULL,
  `source_entry_id` int(10) unsigned DEFAULT NULL,
  `question` varchar(255) NOT NULL,
  `normalized_question` varchar(255) NOT NULL,
  `answer_markdown` mediumtext NOT NULL,
  `answer_plain` mediumtext NOT NULL,
  `answer_html` mediumtext DEFAULT NULL,
  `excerpt` text DEFAULT NULL,
  `audience` varchar(50) NOT NULL DEFAULT 'user',
  `locale` varchar(10) NOT NULL DEFAULT 'it',
  `route_name` varchar(150) DEFAULT NULL,
  `permission_slug` varchar(120) DEFAULT NULL,
  `ranking_weight` smallint(5) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `indexed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_help_entries_module` (`module_id`),
  KEY `idx_help_entries_source_locale` (`source_entry_id`,`locale`),
  KEY `idx_help_entries_active` (`is_active`),
  KEY `idx_help_entries_audience_locale` (`audience`,`locale`),
  KEY `idx_help_entries_question` (`normalized_question`),
  KEY `idx_help_entries_route` (`route_name`),
  KEY `idx_help_entries_permission` (`permission_slug`),
  CONSTRAINT `help_entries_ibfk_1` FOREIGN KEY (`module_id`) REFERENCES `help_modules` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_help_entries_source` FOREIGN KEY (`source_entry_id`) REFERENCES `help_entries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `help_entry_aliases` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entry_id` int(10) unsigned NOT NULL,
  `alias` varchar(255) NOT NULL,
  `normalized_alias` varchar(255) NOT NULL,
  `weight_bonus` smallint(5) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_help_entry_aliases_entry_alias` (`entry_id`,`normalized_alias`),
  KEY `idx_help_entry_aliases_alias` (`normalized_alias`),
  CONSTRAINT `help_entry_aliases_ibfk_1` FOREIGN KEY (`entry_id`) REFERENCES `help_entries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `help_search_terms` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entry_id` int(10) unsigned NOT NULL,
  `term` varchar(120) NOT NULL,
  `normalized_term` varchar(120) NOT NULL,
  `term_type` enum('question','answer','alias','module') NOT NULL DEFAULT 'answer',
  `term_weight` tinyint(3) unsigned NOT NULL DEFAULT 10,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_help_search_terms_entry_term` (`entry_id`,`normalized_term`,`term_type`),
  KEY `idx_help_search_terms_term` (`normalized_term`),
  CONSTRAINT `help_search_terms_ibfk_1` FOREIGN KEY (`entry_id`) REFERENCES `help_entries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `help_queries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `query_text` text NOT NULL,
  `normalized_query` varchar(500) NOT NULL,
  `context_path` varchar(500) DEFAULT NULL,
  `context_module` varchar(100) DEFAULT NULL,
  `matched_entry_id` int(10) unsigned DEFAULT NULL,
  `confidence` tinyint(3) unsigned DEFAULT NULL,
  `response_title` varchar(255) DEFAULT NULL,
  `helpful` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_help_queries_user` (`user_id`),
  KEY `idx_help_queries_context` (`context_module`),
  KEY `idx_help_queries_entry` (`matched_entry_id`),
  KEY `idx_help_queries_helpful` (`helpful`),
  KEY `idx_help_queries_created` (`created_at`),
  CONSTRAINT `help_queries_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `help_queries_ibfk_3` FOREIGN KEY (`matched_entry_id`) REFERENCES `help_entries` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `healthcheck_runs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `total_ok` smallint(5) unsigned NOT NULL DEFAULT 0,
  `total_warn` smallint(5) unsigned NOT NULL DEFAULT 0,
  `total_fail` smallint(5) unsigned NOT NULL DEFAULT 0,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`data`)),
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `healthcheck_runs_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_login_attempts_email` (`email`),
  KEY `idx_login_attempts_ip` (`ip_address`),
  KEY `idx_login_attempts_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mail_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `to_email` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `template` varchar(100) DEFAULT NULL,
  `status` enum('sent','failed','logged') NOT NULL DEFAULT 'logged',
  `error` text DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_mail_log_status` (`status`),
  KEY `idx_mail_log_created` (`created_at`),
  KEY `fk_mail_log_user` (`created_by`),
  CONSTRAINT `fk_mail_log_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mail_templates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) NOT NULL,
  `name` varchar(200) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `body_html` text NOT NULL,
  `variables` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `module` varchar(100) DEFAULT NULL,
  `batch` int(10) unsigned NOT NULL DEFAULT 1,
  `executed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_migrations` (`filename`,`module`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `module_states` (
  `name` varchar(50) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `testing` tinyint(1) NOT NULL DEFAULT 0,
  `updated_by` int(10) unsigned DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`name`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `module_states_ibfk_1` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `module_databases` (
  `module_name` varchar(100) NOT NULL,
  `mode` enum('shared','independent') NOT NULL DEFAULT 'shared',
  `database_name` varchar(64) DEFAULT NULL,
  `host` varchar(255) DEFAULT NULL,
  `port` smallint(5) unsigned DEFAULT NULL,
  `provisioning_status` enum('pending','ready','manual','error','removed') NOT NULL DEFAULT 'pending',
  `last_error` text DEFAULT NULL,
  `last_error_at` timestamp NULL DEFAULT NULL,
  `provisioned_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`module_name`),
  KEY `idx_module_databases_status` (`provisioning_status`),
  KEY `fk_module_databases_user` (`created_by`),
  CONSTRAINT `fk_module_databases_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_channels` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(11) NOT NULL DEFAULT 10,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notification_channels_slug` (`slug`),
  KEY `idx_notification_channels_enabled` (`is_enabled`,`sort_order`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_deliveries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dispatch_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `channel_slug` varchar(50) NOT NULL,
  `status` enum('pending','queued','processing','sent','failed','skipped') NOT NULL DEFAULT 'pending',
  `subject` varchar(255) DEFAULT NULL,
  `body` mediumtext DEFAULT NULL,
  `link` varchar(500) DEFAULT NULL,
  `icon` varchar(150) DEFAULT NULL,
  `color` varchar(32) DEFAULT NULL,
  `provider_message_id` varchar(255) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `attempts` int(10) unsigned NOT NULL DEFAULT 0,
  `sent_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_notification_deliveries_dispatch` (`dispatch_id`),
  KEY `idx_notification_deliveries_user` (`user_id`,`status`),
  KEY `idx_notification_deliveries_channel` (`channel_slug`,`status`),
  CONSTRAINT `fk_notification_deliveries_channel` FOREIGN KEY (`channel_slug`) REFERENCES `notification_channels` (`slug`),
  CONSTRAINT `fk_notification_deliveries_dispatch` FOREIGN KEY (`dispatch_id`) REFERENCES `notification_dispatches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_notification_deliveries_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_dispatches` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event_slug` varchar(150) DEFAULT NULL,
  `source_module` varchar(100) NOT NULL,
  `recipient_user_id` int(10) unsigned DEFAULT NULL,
  `recipient_role_slug` varchar(100) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `body` text DEFAULT NULL,
  `type` enum('info','success','warning','danger') NOT NULL DEFAULT 'info',
  `link` varchar(500) DEFAULT NULL,
  `icon` varchar(150) DEFAULT NULL,
  `color` varchar(32) DEFAULT NULL,
  `payload_json` longtext DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `bypass_preferences` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('pending','queued','sent','partial','failed') NOT NULL DEFAULT 'pending',
  `total_recipients` int(10) unsigned NOT NULL DEFAULT 0,
  `total_deliveries` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_notification_dispatches_event` (`event_slug`),
  KEY `idx_notification_dispatches_status` (`status`,`created_at`),
  KEY `fk_notification_dispatches_created_by` (`created_by`),
  KEY `fk_notification_dispatches_recipient_user` (`recipient_user_id`),
  CONSTRAINT `fk_notification_dispatches_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_notification_dispatches_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_event_channel_bindings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event_type_id` int(10) unsigned NOT NULL,
  `channel_slug` varchar(50) NOT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `subject_template` text DEFAULT NULL,
  `body_template` mediumtext DEFAULT NULL,
  `layout_config` longtext DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notification_event_channel` (`event_type_id`,`channel_slug`),
  KEY `idx_notification_event_channel_enabled` (`channel_slug`,`is_enabled`),
  CONSTRAINT `fk_notification_event_channel_channel` FOREIGN KEY (`channel_slug`) REFERENCES `notification_channels` (`slug`),
  CONSTRAINT `fk_notification_event_channel_event` FOREIGN KEY (`event_type_id`) REFERENCES `notification_event_types` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=231 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_event_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(150) NOT NULL,
  `module_slug` varchar(100) NOT NULL,
  `name` varchar(150) NOT NULL,
  `description` text DEFAULT NULL,
  `context_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`context_schema`)),
  `source` varchar(20) NOT NULL DEFAULT 'dynamic',
  `default_level` enum('info','success','warning','danger') NOT NULL DEFAULT 'info',
  `icon` varchar(150) DEFAULT NULL,
  `color` varchar(32) DEFAULT NULL,
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notification_event_types_slug` (`slug`),
  KEY `idx_notification_event_types_module` (`module_slug`),
  KEY `idx_notification_event_types_system` (`is_system`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_queue` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `delivery_id` int(10) unsigned NOT NULL,
  `channel_slug` varchar(50) NOT NULL,
  `payload_json` longtext DEFAULT NULL,
  `status` enum('pending','processing','sent','failed','skipped') NOT NULL DEFAULT 'pending',
  `available_at` datetime NOT NULL DEFAULT current_timestamp(),
  `locked_at` datetime DEFAULT NULL,
  `attempts` int(10) unsigned NOT NULL DEFAULT 0,
  `max_attempts` int(10) unsigned NOT NULL DEFAULT 5,
  `last_error` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notification_queue_delivery` (`delivery_id`),
  KEY `idx_notification_queue_pending` (`status`,`channel_slug`,`available_at`),
  KEY `fk_notification_queue_channel` (`channel_slug`),
  CONSTRAINT `fk_notification_queue_channel` FOREIGN KEY (`channel_slug`) REFERENCES `notification_channels` (`slug`),
  CONSTRAINT `fk_notification_queue_delivery` FOREIGN KEY (`delivery_id`) REFERENCES `notification_deliveries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` text DEFAULT NULL,
  `type` enum('info','success','warning','danger') NOT NULL DEFAULT 'info',
  `icon` varchar(100) DEFAULT NULL,
  `color` varchar(32) DEFAULT NULL,
  `link` varchar(500) DEFAULT NULL,
  `read_at` timestamp NULL DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notif_user_read` (`user_id`,`read_at`),
  KEY `idx_notif_created` (`created_at`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `fk_notif_sender` (`created_by`),
  CONSTRAINT `fk_notif_sender` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_notif_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `password_history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_pw_history_user` (`user_id`),
  KEY `idx_pw_history_created` (`created_at`),
  CONSTRAINT `password_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `password_resets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `token_hash` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `idx_password_resets_token` (`token_hash`),
  CONSTRAINT `password_resets_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `permissions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `module` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=355 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `php_sessions` (
  `id` varchar(128) NOT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `payload` longtext NOT NULL,
  `last_activity` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_php_sessions_user_id` (`user_id`),
  KEY `idx_php_sessions_last_activity` (`last_activity`),
  CONSTRAINT `fk_php_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `rate_limits` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `rate_key` varchar(128) NOT NULL COMMENT 'user:ID or ip:ADDRESS',
  `endpoint` varchar(255) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_rate_limits_key_endpoint_created` (`rate_key`,`endpoint`,`created_at`),
  KEY `idx_rate_limits_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `report_history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `template_id` int(10) unsigned DEFAULT NULL,
  `template_name` varchar(200) NOT NULL,
  `module` varchar(50) NOT NULL,
  `source_key` varchar(50) NOT NULL,
  `output_format` enum('csv','excel','pdf') NOT NULL,
  `stored_filename` varchar(255) DEFAULT NULL,
  `file_size` int(10) unsigned NOT NULL DEFAULT 0,
  `row_count` int(10) unsigned NOT NULL DEFAULT 0,
  `filters_used` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`filters_used`)),
  `generated_by` int(10) unsigned DEFAULT NULL,
  `generated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `expires_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_history_generated_by` (`generated_by`),
  KEY `idx_history_expires_at` (`expires_at`),
  KEY `idx_history_template_id` (`template_id`),
  CONSTRAINT `report_history_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `report_templates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `report_history_ibfk_2` FOREIGN KEY (`generated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `report_style_presets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `logo_path` varchar(255) DEFAULT NULL,
  `logo_secondary_path` varchar(255) DEFAULT NULL,
  `primary_color` varchar(7) NOT NULL DEFAULT '#3b82f6',
  `secondary_color` varchar(7) NOT NULL DEFAULT '#64748b',
  `accent_color` varchar(7) NOT NULL DEFAULT '#f97316',
  `header_bg_color` varchar(7) NOT NULL DEFAULT '#1e293b',
  `header_text_color` varchar(7) NOT NULL DEFAULT '#ffffff',
  `zebra_color` varchar(7) NOT NULL DEFAULT '#f8fafc',
  `font_family` varchar(100) NOT NULL DEFAULT 'dejavusans',
  `font_size_base` tinyint(3) unsigned NOT NULL DEFAULT 9,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_style_presets_default` (`is_default`),
  CONSTRAINT `report_style_presets_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `report_templates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `module` varchar(50) NOT NULL,
  `source_key` varchar(50) NOT NULL,
  `output_format` enum('csv','excel','pdf') NOT NULL DEFAULT 'pdf',
  `source_type` enum('list','document') NOT NULL DEFAULT 'list',
  `template_html` longtext DEFAULT NULL COMMENT 'GrapeJS HTML template',
  `filters_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`filters_config`)),
  `sorting_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sorting_config`)),
  `style_preset_id` int(10) unsigned DEFAULT NULL,
  `visibility` enum('private','role','global') NOT NULL DEFAULT 'private',
  `visible_to_roles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`visible_to_roles`)),
  `max_rows` int(10) unsigned NOT NULL DEFAULT 10000,
  `bundled_module` varchar(50) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `style_preset_id` (`style_preset_id`),
  KEY `idx_templates_module` (`module`),
  KEY `idx_templates_module_source` (`module`,`source_key`),
  KEY `idx_templates_visibility` (`visibility`),
  KEY `idx_templates_created_by` (`created_by`),
  KEY `idx_templates_bundled` (`bundled_module`),
  KEY `idx_templates_has_html` (`template_html`(100)),
  CONSTRAINT `report_templates_ibfk_1` FOREIGN KEY (`style_preset_id`) REFERENCES `report_style_presets` (`id`) ON DELETE SET NULL,
  CONSTRAINT `report_templates_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `role_constraints` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role_id_1` int(10) unsigned NOT NULL,
  `role_id_2` int(10) unsigned NOT NULL,
  `reason` varchar(500) NOT NULL DEFAULT '',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_rc_pair` (`role_id_1`,`role_id_2`),
  KEY `idx_rc_enabled` (`enabled`),
  KEY `role_id_2` (`role_id_2`),
  CONSTRAINT `role_constraints_ibfk_1` FOREIGN KEY (`role_id_1`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_constraints_ibfk_2` FOREIGN KEY (`role_id_2`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `role_permission` (
  `role_id` int(10) unsigned NOT NULL,
  `permission_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permission_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permission_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `scheduler_jobs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `command` varchar(255) NOT NULL,
  `args_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`args_json`)),
  `interval_minutes` int(10) unsigned NOT NULL DEFAULT 60,
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `last_run_at` datetime DEFAULT NULL,
  `last_status` enum('success','failed','running') DEFAULT NULL,
  `last_output` text DEFAULT NULL,
  `last_output_file` varchar(500) DEFAULT NULL,
  `last_duration_ms` int(10) unsigned DEFAULT NULL,
  `retry_count` int(10) unsigned NOT NULL DEFAULT 0,
  `max_retries` int(10) unsigned NOT NULL DEFAULT 3,
  `next_retry_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_scheduler_jobs_slug` (`slug`),
  KEY `idx_scheduler_jobs_next_retry` (`next_retry_at`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `scheduler_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `job_slug` varchar(100) NOT NULL,
  `started_at` datetime NOT NULL,
  `finished_at` datetime DEFAULT NULL,
  `status` enum('success','failed') NOT NULL,
  `output` text DEFAULT NULL,
  `output_file` varchar(500) DEFAULT NULL,
  `duration_ms` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_scheduler_log_job` (`job_slug`),
  KEY `idx_scheduler_log_started` (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `security_incidents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL COMMENT 'brute_force, csrf_violation, access_denied, etc.',
  `severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  `details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`details`)),
  `ip` varchar(45) DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `resolved_by` int(10) unsigned DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `resolved_by` (`resolved_by`),
  KEY `idx_si_type` (`type`),
  KEY `idx_si_severity` (`severity`),
  KEY `idx_si_ip` (`ip`),
  KEY `idx_si_created` (`created_at`),
  KEY `idx_si_type_created` (`type`,`created_at`),
  CONSTRAINT `security_incidents_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `security_incidents_ibfk_2` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `feedback` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ref_code` varchar(12) NOT NULL,
  `tipo` enum('bug','funzionalita','domanda') NOT NULL DEFAULT 'bug',
  `severita` enum('bassa','media','alta','critica') NOT NULL DEFAULT 'media',
  `stato` enum('nuova','in_lavorazione','risolta','chiusa','non_risolvibile') NOT NULL DEFAULT 'nuova',
  `titolo` varchar(200) DEFAULT NULL,
  `descrizione` text NOT NULL,
  `passi` text DEFAULT NULL,
  `pagina_url` varchar(1000) DEFAULT NULL,
  `route_name` varchar(150) DEFAULT NULL,
  `modulo` varchar(100) DEFAULT NULL,
  `contesto_json` longtext DEFAULT NULL,
  `errori_console_json` text DEFAULT NULL,
  `dom_snapshot` longtext DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `viewport` varchar(40) DEFAULT NULL,
  `app_version` varchar(50) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `assegnata_a` int(10) unsigned DEFAULT NULL,
  `note_admin` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ref_code` (`ref_code`),
  KEY `idx_feedback_stato` (`stato`,`deleted_at`),
  KEY `idx_feedback_tipo` (`tipo`,`deleted_at`),
  KEY `idx_feedback_created` (`created_at`),
  KEY `idx_feedback_modulo` (`modulo`),
  KEY `fk_feedback_assegnato` (`assegnata_a`),
  CONSTRAINT `fk_feedback_creatore` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_feedback_assegnato` FOREIGN KEY (`assegnata_a`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `sessions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `token_hash` varchar(255) NOT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `last_activity` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `expires_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sessions_user` (`user_id`),
  KEY `idx_sessions_token` (`token_hash`),
  KEY `idx_sessions_expires` (`expires_at`),
  CONSTRAINT `sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `telegram_bots` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `bot_username` varchar(100) DEFAULT NULL,
  `bot_token` varchar(255) NOT NULL,
  `webhook_secret` varchar(100) DEFAULT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_telegram_bots_enabled` (`is_enabled`,`is_default`),
  KEY `fk_telegram_bots_created_by` (`created_by`),
  CONSTRAINT `fk_telegram_bots_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `telegram_user_links` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `bot_id` int(10) unsigned NOT NULL,
  `telegram_user_id` varchar(100) DEFAULT NULL,
  `chat_id` varchar(100) DEFAULT NULL,
  `telegram_username` varchar(100) DEFAULT NULL,
  `link_token` varchar(100) NOT NULL,
  `status` enum('pending','linked','revoked') NOT NULL DEFAULT 'pending',
  `linked_at` timestamp NULL DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `metadata_json` longtext DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_telegram_user_links_user_bot` (`user_id`,`bot_id`),
  UNIQUE KEY `uq_telegram_user_links_token` (`link_token`),
  KEY `idx_telegram_user_links_status` (`status`),
  KEY `idx_telegram_user_links_chat` (`chat_id`),
  KEY `fk_telegram_user_links_bot` (`bot_id`),
  CONSTRAINT `fk_telegram_user_links_bot` FOREIGN KEY (`bot_id`) REFERENCES `telegram_bots` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_telegram_user_links_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_folders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `folder` varchar(200) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_folder` (`user_id`,`folder`),
  CONSTRAINT `user_folders_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_notification_preferences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `module_slug` varchar(100) NOT NULL,
  `event_slug` varchar(150) NOT NULL DEFAULT '',
  `channel_slug` varchar(50) NOT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_notification_preference` (`user_id`,`module_slug`,`event_slug`,`channel_slug`),
  KEY `idx_user_notification_preferences_lookup` (`user_id`,`module_slug`,`event_slug`),
  KEY `fk_user_notification_preferences_channel` (`channel_slug`),
  CONSTRAINT `fk_user_notification_preferences_channel` FOREIGN KEY (`channel_slug`) REFERENCES `notification_channels` (`slug`),
  CONSTRAINT `fk_user_notification_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_preferences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `theme` varchar(10) NOT NULL DEFAULT 'light',
  `primary_color` varchar(7) NOT NULL DEFAULT '#3b82f6',
  `sidebar_collapsed` tinyint(1) NOT NULL DEFAULT 0,
  `sidebar_style` varchar(16) NOT NULL DEFAULT 'default',
  `background_pattern` varchar(20) NOT NULL DEFAULT 'circles',
  `theme_skin` varchar(32) NOT NULL DEFAULT 'default',
  `font_family` varchar(32) NOT NULL DEFAULT 'system',
  `language` varchar(5) NOT NULL DEFAULT 'it',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `user_preferences_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=596 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_role` (
  `user_id` int(10) unsigned NOT NULL,
  `role_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `fk_user_role_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_role_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_totp_backup_codes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `code_hash` varchar(255) NOT NULL COMMENT 'bcrypt hash of backup code',
  `used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_utbc_user` (`user_id`),
  CONSTRAINT `user_totp_backup_codes_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_totp_secrets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `secret` varchar(512) NOT NULL COMMENT 'Encrypted TOTP secret (AES-256-GCM via EncryptionService)',
  `algorithm` varchar(10) NOT NULL DEFAULT 'sha1',
  `digits` tinyint(3) unsigned NOT NULL DEFAULT 6,
  `period` tinyint(3) unsigned NOT NULL DEFAULT 30,
  `enabled` tinyint(1) NOT NULL DEFAULT 0,
  `verified_at` timestamp NULL DEFAULT NULL COMMENT 'When user first verified the code',
  `last_used_timestep` bigint(20) unsigned NULL DEFAULT NULL COMMENT 'Ultimo timestep TOTP consumato (counter RFC 6238) - anti-replay',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uts_user` (`user_id`),
  CONSTRAINT `user_totp_secrets_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_widget_preferences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `widget_id` varchar(100) NOT NULL,
  `sort_order` smallint(5) unsigned NOT NULL DEFAULT 0,
  `visible` tinyint(1) NOT NULL DEFAULT 1,
  `size` tinyint(3) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_widget` (`user_id`,`widget_id`),
  KEY `idx_uwp_user_sort` (`user_id`,`sort_order`),
  CONSTRAINT `fk_uwp_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=404 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `must_change_password` tinyint(1) NOT NULL DEFAULT 0,
  `avatar_path` varchar(255) DEFAULT NULL,
  `remember_token` varchar(255) DEFAULT NULL,
  `password_changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_users_remember_token` (`remember_token`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Blog, Documenti, Progetti, Teams (consolidato 2026-07-04) + user_weather_preferences ──
CREATE TABLE IF NOT EXISTS `blog_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(120) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `fk_blog_cat_user` (`created_by`),
  CONSTRAINT `fk_blog_cat_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_articles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(280) NOT NULL,
  `excerpt` varchar(500) DEFAULT NULL,
  `meta_description` varchar(300) DEFAULT NULL,
  `meta_keywords` varchar(255) DEFAULT NULL,
  `og_image` varchar(255) DEFAULT NULL,
  `content` longtext NOT NULL,
  `cover_image` varchar(255) DEFAULT NULL,
  `category_id` int(10) unsigned DEFAULT NULL,
  `status` enum('draft','scheduled','published') NOT NULL DEFAULT 'draft',
  `is_pinned` tinyint(1) NOT NULL DEFAULT 0,
  `visibility` varchar(500) NOT NULL DEFAULT 'all',
  `reading_time` smallint(5) unsigned NOT NULL DEFAULT 0,
  `view_count` int(10) unsigned NOT NULL DEFAULT 0,
  `published_at` timestamp NULL DEFAULT NULL,
  `publish_at` datetime DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `fk_blog_art_cat` (`category_id`),
  KEY `fk_blog_art_user` (`created_by`),
  KEY `idx_blog_art_status` (`status`,`deleted_at`),
  KEY `idx_blog_art_published` (`published_at`),
  KEY `idx_blog_art_pinned` (`is_pinned`,`status`,`deleted_at`),
  KEY `idx_blog_articles_publish_at` (`publish_at`,`status`),
  CONSTRAINT `fk_blog_art_cat` FOREIGN KEY (`category_id`) REFERENCES `blog_categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blog_art_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_article_tags` (
  `article_id` int(10) unsigned NOT NULL,
  `tag_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`article_id`,`tag_id`),
  KEY `fk_blog_at_tag` (`tag_id`),
  CONSTRAINT `fk_blog_at_art` FOREIGN KEY (`article_id`) REFERENCES `blog_articles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_blog_at_tag` FOREIGN KEY (`tag_id`) REFERENCES `blog_tags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_comments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `article_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `body` text NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'approved',
  `moderated_by` int(10) unsigned DEFAULT NULL,
  `moderated_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_blog_com_user` (`user_id`),
  KEY `fk_blog_com_parent` (`parent_id`),
  KEY `idx_blog_com_article` (`article_id`,`deleted_at`),
  KEY `fk_blog_com_mod` (`moderated_by`),
  KEY `idx_blog_com_status` (`article_id`,`status`,`deleted_at`),
  CONSTRAINT `fk_blog_com_art` FOREIGN KEY (`article_id`) REFERENCES `blog_articles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_blog_com_mod` FOREIGN KEY (`moderated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blog_com_parent` FOREIGN KEY (`parent_id`) REFERENCES `blog_comments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_blog_com_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_comment_blacklist` (
  `user_id` int(10) unsigned NOT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `banned_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`user_id`),
  KEY `fk_blog_bl_banned` (`banned_by`),
  CONSTRAINT `fk_blog_bl_banned` FOREIGN KEY (`banned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_blog_bl_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_article_likes` (
  `article_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`article_id`,`user_id`),
  KEY `fk_bal_user` (`user_id`),
  CONSTRAINT `fk_bal_article` FOREIGN KEY (`article_id`) REFERENCES `blog_articles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_bal_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_article_bookmarks` (
  `article_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`article_id`,`user_id`),
  KEY `fk_bab_user` (`user_id`),
  CONSTRAINT `fk_bab_article` FOREIGN KEY (`article_id`) REFERENCES `blog_articles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_bab_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `blog_article_views` (
  `article_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `viewed_on` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`article_id`,`user_id`,`viewed_on`),
  KEY `fk_bav_user` (`user_id`),
  KEY `idx_bav_article_date` (`article_id`,`viewed_on`),
  CONSTRAINT `fk_bav_article` FOREIGN KEY (`article_id`) REFERENCES `blog_articles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_bav_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti_categorie` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `nome` varchar(200) NOT NULL,
  `slug` varchar(220) NOT NULL,
  `codice` varchar(20) NOT NULL COMMENT 'Usato nel protocollo DOC-{CODICE}-{YYYY}-{NNNN}',
  `descrizione` text DEFAULT NULL,
  `colore` varchar(20) DEFAULT NULL,
  `icona` varchar(80) DEFAULT NULL,
  `path` varchar(500) DEFAULT NULL COMMENT 'Path materializzato: /1/5/12/',
  `depth` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `approvazione_richiesta` tinyint(1) NOT NULL DEFAULT 1,
  `reminder_giorni_default` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`reminder_giorni_default`)),
  `ordine` int(10) unsigned NOT NULL DEFAULT 0,
  `created_by` int(10) unsigned DEFAULT NULL,
  `updated_by` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_slug` (`slug`),
  UNIQUE KEY `uk_codice` (`codice`),
  KEY `idx_parent` (`parent_id`),
  CONSTRAINT `fk_categorie_parent` FOREIGN KEY (`parent_id`) REFERENCES `documenti_categorie` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti_files` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `original_name` varchar(500) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `directory` varchar(500) NOT NULL,
  `mime_type` varchar(120) NOT NULL,
  `extension` varchar(20) NOT NULL,
  `size_bytes` bigint(20) unsigned NOT NULL DEFAULT 0,
  `checksum_sha256` char(64) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stored_name` (`stored_name`),
  KEY `idx_checksum` (`checksum_sha256`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `protocollo` varchar(80) DEFAULT NULL,
  `titolo` varchar(500) NOT NULL,
  `descrizione` text DEFAULT NULL,
  `categoria_id` int(10) unsigned NOT NULL,
  `owner_user_id` int(10) unsigned NOT NULL,
  `versione_corrente_id` int(10) unsigned DEFAULT NULL,
  `file_corrente_id` int(10) unsigned DEFAULT NULL,
  `versione_no` int(10) unsigned NOT NULL DEFAULT 0,
  `stato` enum('bozza','inviato','in_controllo','controllato','in_approvazione','approvato','rifiutato','pubblicato','scaduto','archiviato') NOT NULL DEFAULT 'bozza',
  `approvazione_richiesta` tinyint(1) NOT NULL DEFAULT 1,
  `step_corrente` enum('redazione','controllo','approvazione','completato') NOT NULL DEFAULT 'redazione',
  `pubblicato_il` datetime DEFAULT NULL,
  `scade_il` datetime DEFAULT NULL,
  `reminder_giorni` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`reminder_giorni`)),
  `reminder_stage_inviato` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `reminder_ultimo_invio_at` datetime DEFAULT NULL,
  `reminder_destinatari_extra` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`reminder_destinatari_extra`)),
  `lock_user_id` int(10) unsigned DEFAULT NULL,
  `lock_acquired_at` datetime DEFAULT NULL,
  `tag` varchar(500) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `updated_by` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_protocollo` (`protocollo`),
  KEY `idx_categoria` (`categoria_id`),
  KEY `idx_owner` (`owner_user_id`),
  KEY `idx_stato` (`stato`),
  KEY `idx_scade_il` (`scade_il`),
  KEY `idx_pubblicato_il` (`pubblicato_il`),
  KEY `idx_step_corrente` (`step_corrente`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `fk_doc_file_corrente` (`file_corrente_id`),
  KEY `fk_doc_versione_corrente` (`versione_corrente_id`),
  FULLTEXT KEY `ft_titolo_descrizione` (`titolo`,`descrizione`),
  CONSTRAINT `fk_doc_categoria` FOREIGN KEY (`categoria_id`) REFERENCES `documenti_categorie` (`id`),
  CONSTRAINT `fk_doc_file_corrente` FOREIGN KEY (`file_corrente_id`) REFERENCES `documenti_files` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_doc_versione_corrente` FOREIGN KEY (`versione_corrente_id`) REFERENCES `documenti_versioni` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti_versioni` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `documento_id` int(10) unsigned NOT NULL,
  `versione_no` int(10) unsigned NOT NULL,
  `file_id` int(10) unsigned NOT NULL,
  `note_modifica` text DEFAULT NULL,
  `stato` enum('bozza','inviato','in_controllo','controllato','in_approvazione','approvato','rifiutato','pubblicato','sostituito') NOT NULL DEFAULT 'bozza',
  `ripristino_di` int(10) unsigned DEFAULT NULL COMMENT 'Se questa versione è un ripristino, id della versione sorgente',
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `pubblicato_il` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doc_ver` (`documento_id`,`versione_no`),
  KEY `idx_documento_id` (`documento_id`),
  KEY `idx_file_id` (`file_id`),
  KEY `fk_ver_ripristino` (`ripristino_di`),
  CONSTRAINT `fk_ver_documento` FOREIGN KEY (`documento_id`) REFERENCES `documenti` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ver_file` FOREIGN KEY (`file_id`) REFERENCES `documenti_files` (`id`),
  CONSTRAINT `fk_ver_ripristino` FOREIGN KEY (`ripristino_di`) REFERENCES `documenti_versioni` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti_approvazioni` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `documento_id` int(10) unsigned NOT NULL,
  `versione_id` int(10) unsigned DEFAULT NULL,
  `step` enum('redazione','controllo','approvazione') NOT NULL,
  `azione` enum('invia','approva','rifiuta','restituisci','prende_in_carico') NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `note` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_documento` (`documento_id`),
  KEY `idx_versione` (`versione_id`),
  CONSTRAINT `fk_approv_documento` FOREIGN KEY (`documento_id`) REFERENCES `documenti` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_approv_versione` FOREIGN KEY (`versione_id`) REFERENCES `documenti_versioni` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti_collegamenti` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `documento_origine_id` int(10) unsigned NOT NULL,
  `documento_destinazione_id` int(10) unsigned NOT NULL,
  `tipo` enum('correlato','sostituisce','sostituito_da','allegato','riferimento') NOT NULL,
  `note` varchar(500) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collegamento` (`documento_origine_id`,`documento_destinazione_id`,`tipo`),
  KEY `idx_destinazione` (`documento_destinazione_id`),
  CONSTRAINT `fk_coll_destinazione` FOREIGN KEY (`documento_destinazione_id`) REFERENCES `documenti` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_coll_origine` FOREIGN KEY (`documento_origine_id`) REFERENCES `documenti` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_no_self` CHECK (`documento_origine_id` <> `documento_destinazione_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `documenti_protocollo_sequenze` (
  `categoria_id` int(10) unsigned NOT NULL,
  `anno` smallint(5) unsigned NOT NULL,
  `ultimo_numero` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`categoria_id`,`anno`),
  CONSTRAINT `fk_seq_categoria` FOREIGN KEY (`categoria_id`) REFERENCES `documenti_categorie` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `projects` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `client_name` varchar(255) DEFAULT NULL,
  `owner_user_id` int(10) unsigned NOT NULL,
  `status` enum('planning','active','on_hold','completed','cancelled') NOT NULL DEFAULT 'planning',
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `estimated_hours` decimal(10,2) NOT NULL DEFAULT 0.00,
  `budget_planned` decimal(12,2) NOT NULL DEFAULT 0.00,
  `budget_actual_cached` decimal(12,2) NOT NULL DEFAULT 0.00,
  `progress_cached` decimal(5,2) NOT NULL DEFAULT 0.00,
  `teams_conversation_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_projects_code` (`code`),
  KEY `created_by` (`created_by`),
  KEY `idx_projects_status` (`status`),
  KEY `idx_projects_owner` (`owner_user_id`),
  KEY `idx_projects_end_date` (`end_date`),
  KEY `idx_projects_deleted` (`deleted_at`),
  CONSTRAINT `projects_ibfk_1` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `projects_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_milestones` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `billable` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('pending','in_progress','done','missed') NOT NULL DEFAULT 'pending',
  `progress_cached` decimal(5,2) NOT NULL DEFAULT 0.00,
  `calendar_event_id` int(10) unsigned DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_pm_project` (`project_id`),
  KEY `idx_pm_due_date` (`due_date`),
  KEY `idx_pm_status` (`status`),
  CONSTRAINT `project_milestones_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_milestones_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_tasks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL,
  `milestone_id` int(10) unsigned DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `assigned_user_id` int(10) unsigned DEFAULT NULL,
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  `status` enum('todo','in_progress','review','blocked','done') NOT NULL DEFAULT 'todo',
  `start_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `estimated_hours` decimal(10,2) NOT NULL DEFAULT 0.00,
  `position` int(10) unsigned NOT NULL DEFAULT 0,
  `completed_at` timestamp NULL DEFAULT NULL,
  `calendar_event_id` int(10) unsigned DEFAULT NULL,
  `last_reminded_date` date DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_pt_project_status` (`project_id`,`status`),
  KEY `idx_pt_project_due` (`project_id`,`due_date`),
  KEY `idx_pt_assigned_due` (`assigned_user_id`,`due_date`),
  KEY `idx_pt_milestone` (`milestone_id`),
  KEY `idx_pt_calendar` (`calendar_event_id`),
  CONSTRAINT `project_tasks_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_tasks_ibfk_2` FOREIGN KEY (`milestone_id`) REFERENCES `project_milestones` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_tasks_ibfk_3` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_tasks_ibfk_4` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_task_dependencies` (
  `predecessor_task_id` int(10) unsigned NOT NULL,
  `successor_task_id` int(10) unsigned NOT NULL,
  `dependency_type` enum('FS') NOT NULL DEFAULT 'FS',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`predecessor_task_id`,`successor_task_id`),
  KEY `idx_ptd_successor` (`successor_task_id`),
  CONSTRAINT `project_task_dependencies_ibfk_1` FOREIGN KEY (`predecessor_task_id`) REFERENCES `project_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_dependencies_ibfk_2` FOREIGN KEY (`successor_task_id`) REFERENCES `project_tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_members` (
  `project_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `role` enum('owner','member','viewer') NOT NULL DEFAULT 'member',
  `hourly_rate_override` decimal(10,2) DEFAULT NULL,
  `joined_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`project_id`,`user_id`),
  KEY `idx_pmem_user` (`user_id`),
  KEY `idx_pmem_role` (`role`),
  CONSTRAINT `project_members_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_members_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_timesheets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL,
  `task_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `work_date` date NOT NULL,
  `hours` decimal(5,2) NOT NULL,
  `note` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_pts_project_date` (`project_id`,`work_date`),
  KEY `idx_pts_task_date` (`task_id`,`work_date`),
  KEY `idx_pts_user_date` (`user_id`,`work_date`),
  CONSTRAINT `project_timesheets_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_timesheets_ibfk_2` FOREIGN KEY (`task_id`) REFERENCES `project_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_timesheets_ibfk_3` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_files` (
  `project_id` int(10) unsigned NOT NULL,
  `file_id` int(10) unsigned NOT NULL,
  `linked_by` int(10) unsigned DEFAULT NULL,
  `linked_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`project_id`,`file_id`),
  KEY `linked_by` (`linked_by`),
  KEY `idx_pf_file` (`file_id`),
  CONSTRAINT `project_files_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_files_ibfk_2` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_files_ibfk_3` FOREIGN KEY (`linked_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_checklist_templates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pct_created_by` (`created_by`),
  CONSTRAINT `project_checklist_templates_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_checklist_template_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `template_id` int(10) unsigned NOT NULL,
  `label` varchar(500) NOT NULL,
  `position` smallint(5) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_pcti_tpl_pos` (`template_id`,`position`),
  CONSTRAINT `project_checklist_template_items_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `project_checklist_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `project_task_checklist_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `task_id` int(10) unsigned NOT NULL,
  `label` varchar(500) NOT NULL,
  `position` smallint(5) unsigned NOT NULL DEFAULT 0,
  `is_done` tinyint(1) NOT NULL DEFAULT 0,
  `done_at` timestamp NULL DEFAULT NULL,
  `done_by` int(10) unsigned DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `done_by` (`done_by`),
  KEY `created_by` (`created_by`),
  KEY `idx_ptci_task_pos` (`task_id`,`position`),
  KEY `idx_ptci_task_done` (`task_id`,`is_done`),
  CONSTRAINT `project_task_checklist_items_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `project_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_task_checklist_items_ibfk_2` FOREIGN KEY (`done_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `project_task_checklist_items_ibfk_3` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_conversations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('direct','group') NOT NULL DEFAULT 'direct',
  `name` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `avatar_path` varchar(255) DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `archived_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `idx_teams_conv_type` (`type`),
  KEY `idx_teams_conv_archived` (`archived_at`),
  CONSTRAINT `teams_conversations_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_conversation_members` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `conversation_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `role` enum('admin','member') NOT NULL DEFAULT 'member',
  `joined_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `last_read_at` timestamp NULL DEFAULT NULL,
  `notifications_muted` tinyint(1) NOT NULL DEFAULT 0,
  `hidden_at` timestamp NULL DEFAULT NULL,
  `left_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_teams_conv_member` (`conversation_id`,`user_id`),
  KEY `idx_teams_member_user` (`user_id`),
  KEY `idx_teams_member_left` (`left_at`),
  KEY `idx_teams_member_hidden` (`hidden_at`),
  CONSTRAINT `teams_conversation_members_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `teams_conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `teams_conversation_members_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `conversation_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `reply_to_id` int(10) unsigned DEFAULT NULL,
  `body` text NOT NULL,
  `type` enum('text','system') NOT NULL DEFAULT 'text',
  `edited_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `pinned_at` timestamp NULL DEFAULT NULL,
  `pinned_by` int(10) unsigned DEFAULT NULL,
  `state_updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_teams_msg_conv_created` (`conversation_id`,`created_at`),
  KEY `idx_teams_msg_deleted` (`deleted_at`),
  KEY `idx_teams_msg_user` (`user_id`),
  KEY `idx_teams_msg_conv_deleted_created` (`conversation_id`,`deleted_at`,`created_at`),
  KEY `idx_teams_msg_created_deleted` (`created_at`,`deleted_at`),
  KEY `idx_teams_msg_reply` (`reply_to_id`),
  KEY `fk_teams_msg_pinned_by` (`pinned_by`),
  KEY `idx_teams_msg_pinned` (`conversation_id`,`pinned_at`),
  KEY `idx_teams_msg_state` (`conversation_id`,`state_updated_at`),
  FULLTEXT KEY `ft_teams_msg_body` (`body`),
  CONSTRAINT `fk_teams_msg_pinned_by` FOREIGN KEY (`pinned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_teams_msg_reply` FOREIGN KEY (`reply_to_id`) REFERENCES `teams_messages` (`id`) ON DELETE SET NULL,
  CONSTRAINT `teams_messages_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `teams_conversations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `teams_messages_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_user_presence` (
  `user_id` int(10) unsigned NOT NULL,
  `last_seen_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `active_conversation_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  KEY `idx_teams_presence_seen` (`last_seen_at`),
  CONSTRAINT `teams_user_presence_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_typing` (
  `user_id` int(10) unsigned NOT NULL,
  `conversation_id` int(10) unsigned NOT NULL,
  `started_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`user_id`,`conversation_id`),
  KEY `idx_teams_typing_conv` (`conversation_id`),
  CONSTRAINT `teams_typing_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `teams_typing_ibfk_2` FOREIGN KEY (`conversation_id`) REFERENCES `teams_conversations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_message_edits` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `message_id` int(10) unsigned NOT NULL,
  `old_body` text NOT NULL,
  `edited_by` int(10) unsigned DEFAULT NULL,
  `edited_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `edited_by` (`edited_by`),
  KEY `idx_tme_message` (`message_id`),
  CONSTRAINT `teams_message_edits_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `teams_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `teams_message_edits_ibfk_2` FOREIGN KEY (`edited_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_message_reactions` (
  `message_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `emoji` varchar(10) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`message_id`,`user_id`,`emoji`),
  KEY `fk_tmr_user` (`user_id`),
  CONSTRAINT `fk_tmr_message` FOREIGN KEY (`message_id`) REFERENCES `teams_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tmr_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_message_attachments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `message_id` int(10) unsigned NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `mime_type` varchar(150) NOT NULL,
  `size_bytes` bigint(20) unsigned NOT NULL,
  `extension` varchar(20) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_tma_created` (`created_at`),
  KEY `idx_tma_message` (`message_id`),
  CONSTRAINT `teams_message_attachments_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `teams_messages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `teams_message_mentions` (
  `message_id` int(10) unsigned NOT NULL,
  `mentioned_user_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`message_id`,`mentioned_user_id`),
  KEY `idx_tmm_user` (`mentioned_user_id`,`created_at`),
  CONSTRAINT `teams_message_mentions_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `teams_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `teams_message_mentions_ibfk_2` FOREIGN KEY (`mentioned_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `oidc_identities` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `provider` varchar(50) NOT NULL DEFAULT 'oidc',
  `issuer` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `email_at_link` varchar(255) DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_oidc_identity` (`provider`,`issuer`,`subject`),
  UNIQUE KEY `uq_oidc_user_provider` (`user_id`,`provider`),
  CONSTRAINT `fk_oidc_identities_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_weather_preferences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `name` varchar(150) NOT NULL,
  `admin1` varchar(150) DEFAULT NULL,
  `country` varchar(150) DEFAULT NULL,
  `country_code` varchar(10) DEFAULT NULL,
  `latitude` decimal(10,6) NOT NULL,
  `longitude` decimal(10,6) NOT NULL,
  `timezone` varchar(64) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_weather_preferences_user` (`user_id`),
  KEY `idx_user_weather_preferences_lookup` (`user_id`,`name`),
  CONSTRAINT `fk_user_weather_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
